import { addIcon } from '@iconify/vue'
// @ts-expect-error virtual module generated by @nuxt/icon
import { init } from '#build/nuxt-icon-client-bundle'

// Eagerly register @nuxt/icon's client bundle into the iconify store at startup.
//
// By default the bundle is initialized lazily — `init()` only runs the first time
// an icon misses the store and falls into the async `loadIcon` path; the synchronous
// `getIcon` path never initializes it. So a CSS-mode icon mounted during client-side
// navigation (e.g. the docs sidebar section that expands when entering
// /docs/*/directory-structure) resolves its data a microtask late, applies its mask
// CSS after the element has already painted, and flashes a gray `currentColor` box
// for a frame — made more visible by view transitions.
//
// Pre-populating the store here means every bundled icon resolves synchronously, so
// its CSS mounts in the same tick as the element. `init()` is idempotent.
export default defineNuxtPlugin(() => {
  init(addIcon)
})
