shamefullyHoist: true
strictPeerDependencies: false

allowBuilds:
  better-sqlite3: true
  esbuild: true
  rolldown: true
  sharp: true
  "@parcel/watcher": false
  maplibre-gl: false
  puppeteer: false
  unrs-resolver: false
  vue-demi: false
  cbor-extract: true

minimumReleaseAgeExclude:
  - '@nuxt/ui@4.8.0'
