navigation.title: Deployments
title: Nuxt Deployments
description: Discover the different ways to deploy your Nuxt project.
navigation.icon: i-ph-plugs-connected-duotone
links:
  - label: 'Deployment Guide'
    icon: i-ph-cloud-duotone
    to: '/docs/getting-started/deployment'
    color: black
    size: md
