import { parseURL } from 'ufo'
import { rawUrl, getAgentSiteUrl } from '#agent-discovery'
import { CURRENT_DOCS_VERSION } from '#shared/utils/docs'

export default defineNitroPlugin((nitroApp) => {
  // The landing page is a Vue page, so `/raw/index.md` is generated by
  // nuxt-agent-discovery from the discovery registry. This fills in the
  // metadata and body only the site knows.
  nitroApp.hooks.hook('agent-discovery:index', async (event, index) => {
    const domain = getAgentSiteUrl(event)
    const site = await getInstanceAtHead('site')
    const home = (await site.get('/'))?.data as {
      hero?: { title?: string, description?: string }
      features?: { features?: { title: string, description: string }[] }
    } | undefined

    index.title = home?.hero?.title?.replace(/\s+/g, ' ').trim() || 'Nuxt'
    index.description = home?.hero?.description?.replace(/\s+/g, ' ').trim()
      || 'The Intuitive Vue Framework. Build performant and production-grade full-stack web apps and websites with confidence.'

    const featureBullets = (home?.features?.features ?? [])
      .map(feature => `- **${feature.title}**: ${feature.description}`)
      .join('\n')

    index.body.push(
      `## Features

${featureBullets}`,
      `## Getting started

\`\`\`bash
npx nuxi@latest init <project-name>
cd <project-name>
npm install
npm run dev
\`\`\`

- Introduction: <${rawUrl(event, `/docs/${CURRENT_DOCS_VERSION}/getting-started/introduction`)}>
- Installation: <${rawUrl(event, `/docs/${CURRENT_DOCS_VERSION}/getting-started/installation`)}>
- Configuration: <${rawUrl(event, `/docs/${CURRENT_DOCS_VERSION}/getting-started/configuration`)}>`,
      `## Explore

- Documentation: <${domain}/docs>
- Modules: <${rawUrl(event, '/modules')}>
- Templates: <${domain}/templates>
- Showcase: <${domain}/showcase>
- Deploy: <${domain}/deploy>
- Blog: <${domain}/blog/rss.xml>
- Changelog: <${domain}/changelog/rss.xml>
- Team: <${domain}/team>`,
      `## Community

- GitHub: <https://github.com/nuxt/nuxt>
- Discord: <https://chat.nuxt.dev>
- X (Twitter): <https://x.com/nuxt_js>
- Bluesky: <https://bsky.app/profile/nuxt.com>`
    )
  })

  // Pages the content adapter can't know about, plus the same version trim
  // `/sitemap.xml` applies: v3 (legacy) is left out, v5 (nightly) is already
  // excluded through `excludePrefixes`.
  nitroApp.hooks.hook('agent-discovery:sitemap', (event, sections) => {
    const domain = getAgentSiteUrl(event)

    const docs = sections.get('docs')
    if (docs) {
      sections.set('docs', docs.filter(page => !page.href.includes('/docs/3.x/')))
    }

    // Deduplicated against what the adapter already lists: a yml-backed page
    // the comark navigation knows about must not appear twice. The homepage
    // entry comes from `index.yml`, which carries no title of its own.
    const pages = (sections.get('pages') ?? [])
      .map(page => (page.title === '/' ? { ...page, title: 'Home' } : page))
    const listed = new Set(pages.map(page => parseURL(page.href).pathname))
    const extras = [
      { title: 'Home', href: rawUrl(event, '/'), path: '/raw/index.md' },
      { title: 'Showcase', href: `${domain}/showcase`, path: '/showcase' },
      { title: 'Changelog', href: rawUrl(event, '/changelog'), path: '/raw/changelog.md' },
      { title: 'Design system', href: `${domain}/design.md`, path: '/design.md' }
    ].filter(extra => !listed.has(extra.path))

    sections.set('pages', [...extras.map(({ title, href }) => ({ title, href })), ...pages])
  })
})
