import type { NavigationItem, SourceData } from 'comark-content'

/**
 * Navigation item consumed by Nuxt UI content components and site helpers.
 * Extends Comark's NavigationItem with the `titleTemplate` extra used on nuxt.com.
 */
export interface ContentNavigationItem extends NavigationItem {
  titleTemplate?: string
  children?: ContentNavigationItem[]
}

/**
 * Frontmatter shape shared by every versioned docs source.
 * Source data types are generated by `comark-content prepare` (comark-content.d.ts).
 */
export type DocsPageData = SourceData<'docsv3'> & SourceData<'docsv4'> & SourceData<'docsv5'>
